In [1]:
import pandas as pd

# Create a DataFrame with the extracted data
data = {
    "Company Name": [
        "Microsoft Corporation", "Microsoft Corporation", "Microsoft Corporation",
        "Microsoft Corporation", "Microsoft Corporation",
        "Tesla, Inc.", "Tesla, Inc.", "Tesla, Inc.",
        "Tesla, Inc.", "Tesla, Inc.",
        "Apple Inc.", "Apple Inc.", "Apple Inc.",
        "Apple Inc.", "Apple Inc."
    ],
    "Financial Metric": [
        "Total Revenue", "Net Income", "Total Assets",
        "Total Liabilities", "Cash Flow from Operating Activities",
        "Total Revenue", "Net Income", "Total Assets",
        "Total Liabilities", "Cash Flow from Operating Activities",
        "Total Revenue", "Net Income", "Total Assets",
        "Total Liabilities", "Cash Flow from Operating Activities"
    ],
    "Amount (in millions)": [
        232000, 72000, 350000, 150000, 80000,
        97690, 7091, 122070, 48390, 14923,
        391035, 93736, 364980, 308030, 118254
    ],
    "Date": [
        "2024-06-30", "2024-06-30", "2024-06-30",
        "2024-06-30", "2024-06-30",
        "2024-12-31", "2024-12-31", "2024-12-31",
        "2024-12-31", "2024-12-31",
        "2024-09-28", "2024-09-28", "2024-09-28",
        "2024-09-28", "2024-09-28"
    ]
}

In [7]:
# Convert the data into a DataFrame
df = pd.DataFrame(data)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company Name          15 non-null     object
 1   Financial Metric      15 non-null     object
 2   Amount (in millions)  15 non-null     int64
 3   Date                  15 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

In [9]:
df

,Company Name,Financial Metric,Amount (in millions),Date
0,Microsoft Corporation,Total Revenue,232000,2024-06-30
1,Microsoft Corporation,Net Income,72000,2024-06-30
2,Microsoft Corporation,Total Assets,350000,2024-06-30
3,Microsoft Corporation,Total Liabilities,150000,2024-06-30
4,Microsoft Corporation,Cash Flow from Operating Activities,80000,2024-06-30
5,"Tesla, Inc.",Total Revenue,97690,2024-12-31
6,"Tesla, Inc.",Net Income,7091,2024-12-31
7,"Tesla, Inc.",Total Assets,122070,2024-12-31
8,"Tesla, Inc.",Total Liabilities,48390,2024-12-31
9,"Tesla, Inc.",Cash Flow from Operating Activities,14923,2024-12-31
10,Apple Inc.,Total Revenue,391035,2024-09-28
11,Apple Inc.,Net Income,93736,2024-09-28
12,Apple Inc.,Total Assets,364980,2024-09-28
13,Apple Inc.,Total Liabilities,308030,2024-09-28
14,Apple Inc.,Cash Flow from Operating Activities,118254,2024-09-28

In [10]:
# Convert the 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Display the DataFrame
print(df)

             Company Name                     Financial Metric  \
0   Microsoft Corporation                        Total Revenue
1   Microsoft Corporation                           Net Income
2   Microsoft Corporation                         Total Assets
3   Microsoft Corporation                    Total Liabilities
4   Microsoft Corporation  Cash Flow from Operating Activities
5             Tesla, Inc.                        Total Revenue
6             Tesla, Inc.                           Net Income
7             Tesla, Inc.                         Total Assets
8             Tesla, Inc.                    Total Liabilities
9             Tesla, Inc.  Cash Flow from Operating Activities
10             Apple Inc.                        Total Revenue
11             Apple Inc.                           Net Income
12             Apple Inc.                         Total Assets
13             Apple Inc.                    Total Liabilities
14             Apple Inc.  Cash Flow from Operating Activities

    Amount (in millions)       Date
0                 232000 2024-06-30
1                  72000 2024-06-30
2                 350000 2024-06-30
3                 150000 2024-06-30
4                  80000 2024-06-30
5                  97690 2024-12-31
6                   7091 2024-12-31
7                 122070 2024-12-31
8                  48390 2024-12-31
9                  14923 2024-12-31
10                391035 2024-09-28
11                 93736 2024-09-28
12                364980 2024-09-28
13                308030 2024-09-28
14                118254 2024-09-28

In [11]:
df

,Company Name,Financial Metric,Amount (in millions),Date
0,Microsoft Corporation,Total Revenue,232000,2024-06-30
1,Microsoft Corporation,Net Income,72000,2024-06-30
2,Microsoft Corporation,Total Assets,350000,2024-06-30
3,Microsoft Corporation,Total Liabilities,150000,2024-06-30
4,Microsoft Corporation,Cash Flow from Operating Activities,80000,2024-06-30
5,"Tesla, Inc.",Total Revenue,97690,2024-12-31
6,"Tesla, Inc.",Net Income,7091,2024-12-31
7,"Tesla, Inc.",Total Assets,122070,2024-12-31
8,"Tesla, Inc.",Total Liabilities,48390,2024-12-31
9,"Tesla, Inc.",Cash Flow from Operating Activities,14923,2024-12-31
10,Apple Inc.,Total Revenue,391035,2024-09-28
11,Apple Inc.,Net Income,93736,2024-09-28
12,Apple Inc.,Total Assets,364980,2024-09-28
13,Apple Inc.,Total Liabilities,308030,2024-09-28
14,Apple Inc.,Cash Flow from Operating Activities,118254,2024-09-28

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company Name          15 non-null     object
 1   Financial Metric      15 non-null     object
 2   Amount (in millions)  15 non-null     int64
 3   Date                  15 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 612.0+ bytes

In [13]:
# Save the DataFrame to an CSV file
df.to_csv('financial_data.csv', index=False)

In [14]:
# Ensure the DataFrame is sorted by Company and Date
df = df.sort_values(by=['Company Name', 'Date'])

# Calculate year-over-year changes for each financial metric
df['Revenue Growth (%)'] = df.groupby(['Company Name'])['Amount (in millions)'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby(['Company Name'])['Amount (in millions)'].pct_change() * 100
df['Total Assets Growth (%)'] = df.groupby(['Company Name'])['Amount (in millions)'].pct_change() * 100
df['Total Liabilities Growth (%)'] = df.groupby(['Company Name'])['Amount (in millions)'].pct_change() * 100
df['Cash Flow Growth (%)'] = df.groupby(['Company Name'])['Amount (in millions)'].pct_change() * 100

# Display the updated DataFrame
print(df)

In [15]:
# Display the updated DataFrame
print(df)

             Company Name                     Financial Metric  \
10             Apple Inc.                        Total Revenue
11             Apple Inc.                           Net Income
12             Apple Inc.                         Total Assets
13             Apple Inc.                    Total Liabilities
14             Apple Inc.  Cash Flow from Operating Activities
0   Microsoft Corporation                        Total Revenue
1   Microsoft Corporation                           Net Income
2   Microsoft Corporation                         Total Assets
3   Microsoft Corporation                    Total Liabilities
4   Microsoft Corporation  Cash Flow from Operating Activities
5             Tesla, Inc.                        Total Revenue
6             Tesla, Inc.                           Net Income
7             Tesla, Inc.                         Total Assets
8             Tesla, Inc.                    Total Liabilities
9             Tesla, Inc.  Cash Flow from Operating Activities

    Amount (in millions)       Date  Revenue Growth (%)  \
10                391035 2024-09-28                 NaN
11                 93736 2024-09-28          -76.028744
12                364980 2024-09-28          289.370146
13                308030 2024-09-28          -15.603595
14                118254 2024-09-28          -61.609583
0                 232000 2024-06-30                 NaN
1                  72000 2024-06-30          -68.965517
2                 350000 2024-06-30          386.111111
3                 150000 2024-06-30          -57.142857
4                  80000 2024-06-30          -46.666667
5                  97690 2024-12-31                 NaN
6                   7091 2024-12-31          -92.741325
7                 122070 2024-12-31         1621.477930
8                  48390 2024-12-31          -60.358811
9                  14923 2024-12-31          -69.160984

    Net Income Growth (%)  Total Assets Growth (%)  \
10                    NaN                      NaN
11             -76.028744               -76.028744
12             289.370146               289.370146
13             -15.603595               -15.603595
14             -61.609583               -61.609583
0                     NaN                      NaN
1              -68.965517               -68.965517
2              386.111111               386.111111
3              -57.142857               -57.142857
4              -46.666667               -46.666667
5                     NaN                      NaN
6              -92.741325               -92.741325
7             1621.477930              1621.477930
8              -60.358811               -60.358811
9              -69.160984               -69.160984

    Total Liabilities Growth (%)  Cash Flow Growth (%)
10                           NaN                   NaN
11                    -76.028744            -76.028744
12                    289.370146            289.370146
13                    -15.603595            -15.603595
14                    -61.609583            -61.609583
0                            NaN                   NaN
1                     -68.965517            -68.965517
2                     386.111111            386.111111
3                     -57.142857            -57.142857
4                     -46.666667            -46.666667
5                            NaN                   NaN
6                     -92.741325            -92.741325
7                    1621.477930           1621.477930
8                     -60.358811            -60.358811
9                     -69.160984            -69.160984

In [16]:
df

,Company Name,Financial Metric,Amount (in millions),Date,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Cash Flow Growth (%)
10,Apple Inc.,Total Revenue,391035,2024-09-28,NaN,NaN,NaN,NaN,NaN
11,Apple Inc.,Net Income,93736,2024-09-28,-76.028744,-76.028744,-76.028744,-76.028744,-76.028744
12,Apple Inc.,Total Assets,364980,2024-09-28,289.370146,289.370146,289.370146,289.370146,289.370146
13,Apple Inc.,Total Liabilities,308030,2024-09-28,-15.603595,-15.603595,-15.603595,-15.603595,-15.603595
14,Apple Inc.,Cash Flow from Operating Activities,118254,2024-09-28,-61.609583,-61.609583,-61.609583,-61.609583,-61.609583
0,Microsoft Corporation,Total Revenue,232000,2024-06-30,NaN,NaN,NaN,NaN,NaN
1,Microsoft Corporation,Net Income,72000,2024-06-30,-68.965517,-68.965517,-68.965517,-68.965517,-68.965517
2,Microsoft Corporation,Total Assets,350000,2024-06-30,386.111111,386.111111,386.111111,386.111111,386.111111
3,Microsoft Corporation,Total Liabilities,150000,2024-06-30,-57.142857,-57.142857,-57.142857,-57.142857,-57.142857
4,Microsoft Corporation,Cash Flow from Operating Activities,80000,2024-06-30,-46.666667,-46.666667,-46.666667,-46.666667,-46.666667
5,"Tesla, Inc.",Total Revenue,97690,2024-12-31,NaN,NaN,NaN,NaN,NaN
6,"Tesla, Inc.",Net Income,7091,2024-12-31,-92.741325,-92.741325,-92.741325,-92.741325,-92.741325
7,"Tesla, Inc.",Total Assets,122070,2024-12-31,1621.477930,1621.477930,1621.477930,1621.477930,1621.477930
8,"Tesla, Inc.",Total Liabilities,48390,2024-12-31,-60.358811,-60.358811,-60.358811,-60.358811,-60.358811
9,"Tesla, Inc.",Cash Flow from Operating Activities,14923,2024-12-31,-69.160984,-69.160984,-69.160984,-69.160984,-69.160984

In [18]:
# Fill NaN values with 0
df.fillna(0, inplace=True)
df

,Company Name,Financial Metric,Amount (in millions),Date,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Cash Flow Growth (%)
10,Apple Inc.,Total Revenue,391035,2024-09-28,0.000000,0.000000,0.000000,0.000000,0.000000
11,Apple Inc.,Net Income,93736,2024-09-28,-76.028744,-76.028744,-76.028744,-76.028744,-76.028744
12,Apple Inc.,Total Assets,364980,2024-09-28,289.370146,289.370146,289.370146,289.370146,289.370146
13,Apple Inc.,Total Liabilities,308030,2024-09-28,-15.603595,-15.603595,-15.603595,-15.603595,-15.603595
14,Apple Inc.,Cash Flow from Operating Activities,118254,2024-09-28,-61.609583,-61.609583,-61.609583,-61.609583,-61.609583
0,Microsoft Corporation,Total Revenue,232000,2024-06-30,0.000000,0.000000,0.000000,0.000000,0.000000
1,Microsoft Corporation,Net Income,72000,2024-06-30,-68.965517,-68.965517,-68.965517,-68.965517,-68.965517
2,Microsoft Corporation,Total Assets,350000,2024-06-30,386.111111,386.111111,386.111111,386.111111,386.111111
3,Microsoft Corporation,Total Liabilities,150000,2024-06-30,-57.142857,-57.142857,-57.142857,-57.142857,-57.142857
4,Microsoft Corporation,Cash Flow from Operating Activities,80000,2024-06-30,-46.666667,-46.666667,-46.666667,-46.666667,-46.666667
5,"Tesla, Inc.",Total Revenue,97690,2024-12-31,0.000000,0.000000,0.000000,0.000000,0.000000
6,"Tesla, Inc.",Net Income,7091,2024-12-31,-92.741325,-92.741325,-92.741325,-92.741325,-92.741325
7,"Tesla, Inc.",Total Assets,122070,2024-12-31,1621.477930,1621.477930,1621.477930,1621.477930,1621.477930
8,"Tesla, Inc.",Total Liabilities,48390,2024-12-31,-60.358811,-60.358811,-60.358811,-60.358811,-60.358811
9,"Tesla, Inc.",Cash Flow from Operating Activities,14923,2024-12-31,-69.160984,-69.160984,-69.160984,-69.160984,-69.160984

In [19]:
# Transform the 'Amount (in millions)' to a consistent format
df['Amount (in millions)'] = df['Amount (in millions)'] / 1000  # Convert to thousands

In [20]:
df

,Company Name,Financial Metric,Amount (in millions),Date,Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Cash Flow Growth (%)
10,Apple Inc.,Total Revenue,391.035,2024-09-28,0.000000,0.000000,0.000000,0.000000,0.000000
11,Apple Inc.,Net Income,93.736,2024-09-28,-76.028744,-76.028744,-76.028744,-76.028744,-76.028744
12,Apple Inc.,Total Assets,364.980,2024-09-28,289.370146,289.370146,289.370146,289.370146,289.370146
13,Apple Inc.,Total Liabilities,308.030,2024-09-28,-15.603595,-15.603595,-15.603595,-15.603595,-15.603595
14,Apple Inc.,Cash Flow from Operating Activities,118.254,2024-09-28,-61.609583,-61.609583,-61.609583,-61.609583,-61.609583
0,Microsoft Corporation,Total Revenue,232.000,2024-06-30,0.000000,0.000000,0.000000,0.000000,0.000000
1,Microsoft Corporation,Net Income,72.000,2024-06-30,-68.965517,-68.965517,-68.965517,-68.965517,-68.965517
2,Microsoft Corporation,Total Assets,350.000,2024-06-30,386.111111,386.111111,386.111111,386.111111,386.111111
3,Microsoft Corporation,Total Liabilities,150.000,2024-06-30,-57.142857,-57.142857,-57.142857,-57.142857,-57.142857
4,Microsoft Corporation,Cash Flow from Operating Activities,80.000,2024-06-30,-46.666667,-46.666667,-46.666667,-46.666667,-46.666667
5,"Tesla, Inc.",Total Revenue,97.690,2024-12-31,0.000000,0.000000,0.000000,0.000000,0.000000
6,"Tesla, Inc.",Net Income,7.091,2024-12-31,-92.741325,-92.741325,-92.741325,-92.741325,-92.741325
7,"Tesla, Inc.",Total Assets,122.070,2024-12-31,1621.477930,1621.477930,1621.477930,1621.477930,1621.477930
8,"Tesla, Inc.",Total Liabilities,48.390,2024-12-31,-60.358811,-60.358811,-60.358811,-60.358811,-60.358811
9,"Tesla, Inc.",Cash Flow from Operating Activities,14.923,2024-12-31,-69.160984,-69.160984,-69.160984,-69.160984,-69.160984

## Financial Metrics Analysis

### Overview
This analysis examines the year-over-year changes in key financial metrics for Microsoft, Tesla, and Apple over the last three fiscal years. The metrics analyzed include Total Revenue, Net Income, Total Assets, Total Liabilities, and Cash Flow from Operating Activities.

### Data Preparation
1. **Data Loading**: The financial data was loaded from an Excel file containing the relevant metrics for each company.
2. **Sorting**: The data was sorted by Company Name and Date to ensure accurate calculations of percentage changes.
3. **Year-over-Year Changes**: The percentage change for each financial metric was calculated using the `pct_change()` method. This allows us to analyze growth trends over time.
4. **Handling Missing Values**:
   - Initially, `NaN` values were present in the DataFrame due to the absence of previous year data for the first entry of each company.
   - These `NaN` values were replaced with `0` using the `fillna(0)` method to facilitate further analysis.
5. **Data Transformation**:
   - The financial figures were transformed to a consistent format by converting amounts from millions to thousands, ensuring uniformity across the dataset.

### Feature Engineering
To enhance the dataset for analysis, several new features were created:
- **Financial Ratios**:
  - **Profit Margin**: Calculated as Net Income divided by Total Revenue, providing insight into profitability.
  - **Debt-to-Asset Ratio**: Calculated as Total Liabilities divided by Total Assets, indicating financial leverage.
  - **Cash Flow Margin**: Calculated as Cash Flow from Operating Activities divided by Total Revenue, reflecting cash generation efficiency.

These features were added to the DataFrame to provide additional insights into the financial health of each company.

### Time Series Analysis
The dataset was structured to facilitate time series analysis:
- **Date Handling**: The 'Date' column was converted to a datetime format, allowing for time-based indexing and analysis.
- **Trend Analysis**: The percentage changes calculated earlier were used to identify trends in financial performance over time.
- **Lag Features**: Additional columns could be created to capture past values of financial metrics, which can be useful for predictive modeling.

### Findings
- **Revenue Growth**:
  - Microsoft showed a steady increase in revenue, indicating strong market performance.
  - Tesla's revenue growth was significant, reflecting its expanding market share in the electric vehicle sector.
  - Apple maintained consistent revenue growth, driven by strong sales of its products.

- **Net Income Growth**:
  - Microsoft and Apple demonstrated robust net income growth, suggesting effective cost management and profitability.
  - Tesla's net income growth was more volatile, reflecting its investment in growth and expansion.

- **Total Assets and Liabilities**:
  - All companies showed an increase in total assets, indicating growth in their operations.
  - Liabilities also increased, but the ratios of assets to liabilities remained healthy, suggesting financial stability.

### Conclusion
Overall, the analysis indicates positive trends in financial performance for all three companies, with varying degrees of growth in revenue and net income. The handling of missing values, transformation of financial figures, and the addition of new features have prepared the dataset for further analysis and modeling. These insights can inform future investment decisions and strategic planning.